---
# The port to listen on.
dns_port: 53

# Should the DNS server be a caching DNS server?
dns_caching_dns: yes

dns_options_forwarders:
  - 1.1.1.1
  - 8.8.8.8

# A list of zones and properties per zone.
dns_zones:
  - name: localhost
    soa: localhost
    serial: 1
    refresh: 604800
    retry: 86400
    expire: 2419200
    ttl: 604800
    records:
      - name: "@"
        type: NS
        value: localhost.
      - name: "@"
        value: 127.0.0.1
      - name: "@"
        type: AAAA
        value: ::1

  - name: 127.in-addr.arpa
    ttl: 604800
    records:
      - name: "@"
        type: NS
        value: localhost.
      - name: 1.0.0
        type: PTR
        value: localhost.

  - name: 0.in-addr.arpa
    records:
      - name: "@"
        type: NS
        value: localhost.

  - name: 255.in-addr.arpa
    records:
      - name: "@"
        type: NS
        value: localhost.

  - name: stoeps.home
    ttl: 604800
    ns:
      - name: cnx-ns.stoeps.home.
    mx:
      - name: cnx-mail.stoeps.home.
        priority: 10
    records:
      - name: cnx-ns
        value: 10.0.22.2
      - name: cnx-nfs
        value: 10.0.22.3
      - name: cnx-ds
        value: 10.0.22.4
      - name: cnx65-was
        value: 10.0.22.30
      - name: cnx65-db2
        value: 10.0.22.31
      - name: cnx65
        value: 10.0.22.32
      - name: cnx65-cp
        value: 10.0.22.35
      - name: cnx7-was
        value: 10.0.22.40
      - name: cnx7-db2
        value: 10.0.22.41
      - name: cnx7
        value: 10.0.22.42
      - name: cnx7-cp
        value: 10.0.22.45
      - name: a21c-was1
        value: 10.0.22.50
      - name: stoeps.home.
        value: 10.0.22.50
      - name: a21c-was2
        value: 10.0.22.51
      - name: a21c-db2
        value: 10.0.22.52
      - name: a21c-nfs
        value: 10.0.22.53

# An optional list of acls to allow recursion. ("any" and "none" are always available.)
# dns_allow_recursion:
#  - none

# An optional list of IPv4 on which the DNS server will listen. ("any" and "none" are always available.)
dns_options_listen_on:
  - any

# A optional list of IPv6 on which the DNS server will listen. ("any" and "none" are always available.)
dns_options_listen_on_v6:
  - any

# An optional setting to configure the path where the pid file will be created.
dns_pid_file: /run/named/named.pid

